sudo: false

language: ruby
before_script:
  - cp test/database.ci.yml test/database.yml
  - psql -c 'CREATE DATABASE ltree_hierarchy_test;' -U postgres
branches:
  only:
    - master
rvm:
  - 2.3.3
  - rbx
  - jruby-19mode
gemfile:
  - test/gemfiles/Gemfile.rails-4.2.x
  - test/gemfiles/Gemfile.rails-5.0.x
